default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: getnewspeak_development

test:
  <<: *default
  database: getnewspeak_test

production:
  <<: *default
  database: getnewspeak_production
  password: <%= ENV['GETNEWSPEAK_DATABASE_PASSWORD'] %>
