# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de4e1b663c270072a4ff462b9035f95a1fed4828518d1be07cedd02b4226de0a6dbeebda69975b292a4d7356728074239c99d93c186e022367f72a0dbd4d42be

test:
  secret_key_base: 54e726a2477aaf6da3e037417d1a3df8877176ff7bf21970deb7fdf1038b7066ab2edde1b65ba6d6826e48cbd87a8c695868d544c5879b2cc2bc43adec76827e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
